name: Caliper test
version: '2.0.0'

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: fixed-asset

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/3e142e05e6d795074ccd92ad97c9b90e094caf2960f1b99afec30d8241655c71_sk'
          clientSignedCert:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: /home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org1.example.com/connection-org1.json
      discover: true
