name: Caliper test
version: '2.0.0'

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: fixed-asset

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/0d380be012ce8f9433e4be99c823faef677f34f387241480b6f4b3a8e819fede_sk'
          clientSignedCert:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: /home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org1.example.com/connection-org1.json
      discover: true

  - mspid: Org2MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/7636db89c09256d2c1b2b5c05a7a06502e1b21b665836cfa5cb82bb5e977f438_sk'
          clientSignedCert:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: /home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org2.example.com/connection-org2.json
      discover: true

  - mspid: Org3MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/e837784acda98c21b32389c48acbff4975144fd69839760dd213072b7f839a1a_sk'
          clientSignedCert:
            path: '/home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: /home/bstudent/dev/hyperledger-fabric-performance-improvement/network/organizations/peerOrganizations/org3.example.com/connection-org3.json
      discover: true
